### PR TITLE
Fixing a bug in client.py that causes a warning

### PR DESCRIPTION
**Pull request by itsVale**
My Python version: 3.6.5
My AIOHTTP version: 3.2.1
My websockets version: 5.0.1

I was just using GiphyPy and recieved the error 
`RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self.session.close()`.

aiohttp.ClientSession.close became a coroutine a few months ago I think.

### CODE REVIEW

**Comment by MichaelYusko** [comment]
@itsVale Thank you,  for the your patch! @nik849 could you make a new release? with the new changes.

**Comment by itsVale** [comment]
I wanted to add something additional. Later I tried to use GiphyPy to add a command to my Discord bot that searches and sends a random gif from Giphy with the given search word. I noticed that after using the command one time, the command is unusable since the session doesn't open again. I had to remove the line that closes the ClientSession completely to get it working properly. But I'd suggest to add a check if there's already a ClientSession when making a request to the API and if not, create a new ClientSession.

**Comment by MichaelYusko** [comment]
@itsVale Amazing! thank you for the your contribution, I'll review your PR, when you will make a a new one, and in this time we need to wait @nik849 for uploading an new version on `PyPi` 👍

**Comment by MichaelYusko** [comment]
@itsVale PR merged, but still waiting for @nik849

**Pull request merged**
